// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/dense-chunking-only/20260930T113012Z.json (corpus run 20260930T113012Z),
// envelope lab-lossless-capture/1, orchestrator v4.7.0, observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const denseChunkingOnlyFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-09-30T11:30:21.409Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/3"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SAHOAPKP.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/dense-lib": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/dense-lib": "_nf_lab_dense_lib.fJdoGqXTjq.js"
                  },
                  "cached": true,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/dense-lib",
                      "file": "_nf_lab_dense_lib.fJdoGqXTjq.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/dense-lib/extra": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/dense-lib/extra": "_nf_lab_dense_lib_extra.IKoP9vbCZc.js"
                  },
                  "cached": true,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/dense-lib/extra",
                      "file": "_nf_lab_dense_lib_extra.IKoP9vbCZc.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/utils": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/utils": "_nf_lab_utils.wMYw37SmBF.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/utils",
                      "file": "_nf_lab_utils.wMYw37SmBF.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "mfe1",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/utils": "_nf_lab_utils.wMYw37SmBF.js"
                  },
                  "cached": false,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/utils",
                      "file": "_nf_lab_utils.wMYw37SmBF.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "mfe1": {
        "browser-shared": [
          "chunk-Y6UYBMA7.js"
        ],
        "mapping-or-exposed": []
      }
    },
    "generation": "v4.5",
    "orchestratorVersion": "4.7.0"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 4,
        "scopeCount": 1,
        "imports": [
          {
            "specifier": "@nf-lab/dense-lib",
            "target": "./mfe1/_nf_lab_dense_lib.fJdoGqXTjq.js"
          },
          {
            "specifier": "@nf-lab/dense-lib/extra",
            "target": "./mfe1/_nf_lab_dense_lib_extra.IKoP9vbCZc.js"
          },
          {
            "specifier": "@nf-lab/utils",
            "target": "./_nf_lab_utils.wMYw37SmBF.js"
          },
          {
            "specifier": "mfe1/./main",
            "target": "./mfe1/main-SAHOAPKP.js"
          }
        ],
        "scopes": [
          {
            "scope": "./mfe1/",
            "imports": [
              {
                "specifier": "@nf-internal/chunk-Y6UYBMA7",
                "target": "./mfe1/chunk-Y6UYBMA7.js"
              }
            ]
          }
        ],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/dense-lib",
          "target": "http://localhost:4300/mfe1/_nf_lab_dense_lib.fJdoGqXTjq.js"
        },
        {
          "specifier": "@nf-lab/dense-lib/extra",
          "target": "http://localhost:4300/mfe1/_nf_lab_dense_lib_extra.IKoP9vbCZc.js"
        },
        {
          "specifier": "@nf-lab/utils",
          "target": "http://localhost:4300/_nf_lab_utils.wMYw37SmBF.js"
        },
        {
          "specifier": "mfe1/./main",
          "target": "http://localhost:4300/mfe1/main-SAHOAPKP.js"
        }
      ],
      "scopes": [
        {
          "scope": "http://localhost:4300/mfe1/",
          "imports": [
            {
              "specifier": "@nf-internal/chunk-Y6UYBMA7",
              "target": "http://localhost:4300/mfe1/chunk-Y6UYBMA7.js"
            }
          ]
        }
      ],
      "integrityFor": []
    }
  },
  "errors": []
};
