// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/dynamic-override/20260811T095734Z.json (corpus run 20260816T182544Z),
// envelope lab-lossless-capture/1, orchestrator v4.6.0 (8e5e0b3), observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const dynamicOverrideFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-08-11T09:58:05.344Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/4"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtimeSource": {
    "storage": "globalThis",
    "namespace": "__NATIVE_FEDERATION__",
    "discovery": "default",
    "orchestratorVersion": null,
    "otherNamespaces": []
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./Component",
            "file": "Component-RJXV7SVT.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/conflict-lib": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.0.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.jvcc6K1csg.js"
                  },
                  "cached": true,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.jvcc6K1csg.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                  },
                  "cached": false,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "mfe1": {
        "mapping-or-exposed": []
      },
      "__NF-HOST__": {
        "mapping-or-exposed": []
      }
    },
    "generation": "v4.5"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap",
        "parsed": true,
        "importCount": 2,
        "scopeCount": 0,
        "imports": [
          {
            "specifier": "@nf-lab/conflict-lib",
            "target": "./_nf_lab_conflict_lib.jvcc6K1csg.js"
          },
          {
            "specifier": "mfe1/./Component",
            "target": "./mfe1/Component-RJXV7SVT.js"
          }
        ],
        "scopes": [],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [],
      "scopes": [],
      "integrityFor": []
    }
  },
  "errors": []
};
