// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/dynamic-init-shim/20260811T095614Z.json (corpus run 20260816T182544Z),
// envelope lab-lossless-capture/1, orchestrator v4.6.0 (8e5e0b3), observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const dynamicInitShimFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-08-11T09:56:47.357Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/4"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtimeSource": {
    "storage": "globalThis",
    "namespace": "__NATIVE_FEDERATION__",
    "discovery": "default",
    "orchestratorVersion": null,
    "otherNamespaces": []
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./Component",
            "file": "Component-RJXV7SVT.js"
          }
        ],
        "integrity": {
          "_nf_lab_conflict_lib.JF7uEdSVsN.js": "sha384-YzSmpZn3CZ6us9IawjsujujyYXGN6i5Tkev0sl+S99x81IEVGuamUeQD1qfRLT2L",
          "Component-RJXV7SVT.js": "sha384-aDdQ8FmNPkw5O84YvEXmIuU6/v3MMTaOeBI4FdVifv02iDXaJxWLXSq333+oWInw"
        }
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      },
      "mfe2": {
        "scopeUrl": "./mfe2/",
        "exposes": [
          {
            "moduleName": "./Component",
            "file": "Component-52VOYNCY.js"
          }
        ],
        "integrity": {
          "_nf_lab_conflict_lib.jvcc6K1csg.js": "sha384-rN4JDxmCuqtOCX80/olE4QQjGHSN3qCLyXQpEreM0atoIBJ9uXY/XbsGekChWdRl",
          "Component-52VOYNCY.js": "sha384-n93aw505e2EWoWC2/K8bbUa+TLfAGSP7JMMCwPZyKzj41f+0TTNvVy99N//aGIU+"
        }
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/conflict-lib": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.0.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "mfe2",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.jvcc6K1csg.js"
                  },
                  "cached": false,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.jvcc6K1csg.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/conflict-lib": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                  },
                  "cached": true,
                  "bundle": "browser-shared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/conflict-lib",
                      "file": "_nf_lab_conflict_lib.JF7uEdSVsN.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "mfe1": {
        "mapping-or-exposed": []
      },
      "__NF-HOST__": {
        "mapping-or-exposed": []
      },
      "mfe2": {
        "mapping-or-exposed": []
      }
    },
    "generation": "v4.5"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 2,
        "scopeCount": 0,
        "imports": [
          {
            "specifier": "@nf-lab/conflict-lib",
            "target": "./mfe1/_nf_lab_conflict_lib.JF7uEdSVsN.js"
          },
          {
            "specifier": "mfe1/./Component",
            "target": "./mfe1/Component-RJXV7SVT.js"
          }
        ],
        "scopes": [],
        "integrity": {
          "./mfe1/_nf_lab_conflict_lib.JF7uEdSVsN.js": "sha384-YzSmpZn3CZ6us9IawjsujujyYXGN6i5Tkev0sl+S99x81IEVGuamUeQD1qfRLT2L",
          "./mfe1/Component-RJXV7SVT.js": "sha384-aDdQ8FmNPkw5O84YvEXmIuU6/v3MMTaOeBI4FdVifv02iDXaJxWLXSq333+oWInw"
        }
      },
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 1,
        "scopeCount": 0,
        "imports": [
          {
            "specifier": "mfe2/./Component",
            "target": "./mfe2/Component-52VOYNCY.js"
          }
        ],
        "scopes": [],
        "integrity": {
          "./mfe2/Component-52VOYNCY.js": "sha384-n93aw505e2EWoWC2/K8bbUa+TLfAGSP7JMMCwPZyKzj41f+0TTNvVy99N//aGIU+"
        }
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/conflict-lib",
          "target": "http://localhost:4300/mfe1/_nf_lab_conflict_lib.JF7uEdSVsN.js"
        },
        {
          "specifier": "mfe1/./Component",
          "target": "http://localhost:4300/mfe1/Component-RJXV7SVT.js"
        },
        {
          "specifier": "mfe2/./Component",
          "target": "http://localhost:4300/mfe2/Component-52VOYNCY.js"
        }
      ],
      "scopes": [],
      "integrityFor": [
        "http://localhost:4300/mfe1/_nf_lab_conflict_lib.JF7uEdSVsN.js",
        "http://localhost:4300/mfe1/Component-RJXV7SVT.js",
        "http://localhost:4300/mfe2/Component-52VOYNCY.js"
      ]
    }
  },
  "errors": []
};
