// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/frankenstein-live/20260811T115536Z-01-initial.json — the public deployment
// https://lutzleonhardt.de/frankenstein-meeting-room/ captured 2026-08-11
// (deployment-dependent, not regenerable from checkouts; see
// captures/frankenstein-live/provenance.json). Released orchestrator generation
// (v4, `file`-spelling participants), best-known @softarc/native-federation-orchestrator ^4.0.0.
// The corpus validator enforces the two capture phases byte-identical, so this
// one fixture represents both.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const frankensteinLiveFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "https://lutzleonhardt.de/frankenstein-meeting-room/",
    "capturedAt": "2026-08-11T11:56:25.504Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/4"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtimeSource": {
    "storage": "globalThis",
    "namespace": "__NATIVE_FEDERATION__",
    "discovery": "default",
    "orchestratorVersion": null,
    "otherNamespaces": []
  },
  "runtime": {
    "remotes": {
      "whiteboard": {
        "scopeUrl": "./whiteboard/",
        "exposes": [
          {
            "moduleName": "./Bootstrap",
            "file": "Bootstrap-7COJRA5I.js"
          }
        ],
        "integrity": {
          "_excalidraw_excalidraw.0MlOv2WvQj.js": "sha384-gQrm6C7mOLCTYcdQFNBrh7GZ3o5hy2K2NmxwOfiJtDzs7NTkKc5hTxSBfksuKbaU",
          "react.QYXZqQxJ1j.js": "sha384-57khIiCnWo5tC9kEt0ibpdoHhHGtPXp1KmeWeJyyX0+UPwenA+Wj+0qvj7ajI3As",
          "react_jsx_runtime.RDhwXXoxCg.js": "sha384-mWHwomGyGtSC45UesaeI3hV4diuzv10CMDSAWJ1rMRQ8F+lA71uneBirgsCW/JxO",
          "react_jsx_dev_runtime.UsMOGvdsKw.js": "sha384-Pz3qELNqQbfKZe26gJ2n/S9ZKDnDcKoBB4HKdEphutzsxBeMedPySvP+iKitw5h/",
          "react_dom.6SKyvL_ZIW.js": "sha384-P5wEc9b7LWwq+gIw6WZydAmGaqqKM9f1+8HOET0FxnhMqtpfCs6opvzQAXMtoyZA",
          "react_dom_client.lVKcx-4-HL.js": "sha384-qhRGasTGrIXFNZJfwVfTnDA2+KKAGE/O6D+GEErqa6n/c3xiyVcKH1x4FmMqeUAN",
          "react_dom_profiling.wPFH8wjIJf.js": "sha384-ljYfxwXdL20/jno4xQm1XDO5sL/8huAbZHNBeJ4Ov+nY5UDdOHl3ZwurHwevUCdI",
          "Bootstrap-7COJRA5I.js": "sha384-7/Brmjo9gqN65lCvoMCfm1Ub5tyUw3ivabWA1NeC/UJOUrWzlfhIj0XYoFKiFEk7"
        }
      },
      "mermaid": {
        "scopeUrl": "./mermaid/",
        "exposes": [
          {
            "moduleName": "./Bootstrap",
            "file": "Bootstrap-BBNZEAEH.js"
          }
        ],
        "integrity": {
          "mermaid.fMI3T940QA.js": "sha384-kstnQo1tIfL+tMgIsAHgtN6HODg7IUJOB7YxDsvWEfQKwtm2T8pJXYurn7ZK8lW/",
          "Bootstrap-BBNZEAEH.js": "sha384-DPpBRZv47CVBpYfzVQiKWL76+Zh+GNRvDSY7G99RMPT+j5U8Pq7eDciHllDgRaFO"
        }
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {
          "_angular_common.Ucn2BmyRM1.js": "sha384-ifIpCfW3pytDYCF1JasK/q29l9JcykVZmVSQPMbvfrIGyBjplklPOyLqxyHVtqL7",
          "_angular_common_http.XnycUwbhpt.js": "sha384-IK8Nx+6NWCVROXYGp+8jufFYVZlMcU0/sA2pO54JMRAhwQCS6iZuRCEnwvAGIG0O",
          "chunk-WW26EZ22.js": "sha384-sDhcZ7eQ+i0rEfRIZ4dhGpwqqr4OLIKhrNr1CpqUuynnbsK2qpp/I/cq8JVcKfl0",
          "_angular_platform_browser.lAyP2N3Pw8.js": "sha384-Uqk4Pa50G3bzBAWwoZ0rCBacNLN2dyJ8QkJWL5QD6IqFLISZIk84SZzH8RmcXGlk",
          "rxjs.IJzVNeB5rY.js": "sha384-CND2UMO83rk1q4PmwPBkMzMidBFPpleOKv8RwUTYv7MVKgLY5QZ4rSMNPkizOXfU",
          "rxjs_operators.gdYSvUruih.js": "sha384-laChUqH6WQnng9RMXX09mNVUEHCCL/2hiynx8XKFxv8EpZDOXvUI6j2KJAvkz7/m",
          "chunk-PAMKM67I.js": "sha384-hTdulOFDbDpZPDXTPSqo9asD5kf/Rb2nqqOwqK/IzWWXyf8kf0+N94FSvSjPLKtF",
          "tslib.s6WVYyl__v.js": "sha384-us48hLnAuTVi42myNvtbK0UsmSvbAjKfiZP4HjtL9tB6FogW0rizxqZPIRAbidzm",
          "_angular_core.RHjtWEkOzP.js": "sha384-K67ZQ5cbnDPIVn8WANbSD0mtv1yJTMx8mlSOumXJTrAgTrsuRNsDWfVtimzbGc8o",
          "_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js": "sha384-5wVWeVYtx1cBT1jKmN8rQ7UM9OvfVXX8EiLwaa0Ske0MZEGspZWPPZzpPCmI7TvV",
          "_angular_core_primitives_di.QUc60-Xs6C.js": "sha384-6rOmacKn8k2Rcgtrc+9Jiv4npsCyzrhos2r3DUvquC7Sy2zH1Qe8r7CLOIaKbfoP",
          "_angular_core_primitives_event_dispatch.1A9qBws3LP.js": "sha384-MD1dEWUryHtZl1bJtQZQD2JHywLtf2noRB7QrVRtzO/zWxi/9bmM02zYvzWXySQM",
          "chunk-RCIWTGS7.js": "sha384-GVoyZ7htW1QcYMK3i6Pio7FhoQCY+94M+cYKVVTZyrTUO6RQKqRpVu5T2ng478ha",
          "_angular_core_primitives_signals.ePwPWbaXlE.js": "sha384-LPA4je4R4YerkZL5Dsogc8kPstf4JOzHn1RFaf8Pv5R+mNyYS3zwhgqy7LAAZePH",
          "_angular_core_rxjs_interop.YqevhcoUQy.js": "sha384-ZmQah/VqzvO07m4LLHnI5ixj/1rxctq98QHEfgknKEma3JSgXejbnkph+m/WfWmc",
          "chunk-K6ZMRNMW.js": "sha384-aZwtRvM310GrKNMB9tX07AS1Chpy7tOFkHUfDaJP+pAlU7dOs4PIXTpIFLeObnGV",
          "chunk-APTZXQMF.js": "sha384-zWhh2apMCPktoaZjn6P/SeGHLy7ujJxm4zqpRZ0BLIciAD+DEHbQgnzCu06YN4vy",
          "chunk-V2SUVJ7R.js": "sha384-BfAKYP5/8tfHP2fbRCyG4x5an/HWTuOKp4XtnZoJwWpXoctwT6gkvA4/b7qHWizn",
          "chunk-2VMXMS7J.js": "sha384-IiJwn+tZf8TQkKyCcaAtb9JW90aZbS2eLcLYxvXmc4DKIkLJGSPoVR4c+hMZ/hi2"
        }
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@excalidraw/excalidraw": {
          "dirty": false,
          "versions": [
            {
              "tag": "0.18.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "~0.18.1",
                  "strictVersion": true,
                  "file": "_excalidraw_excalidraw.0MlOv2WvQj.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_excalidraw_excalidraw.0MlOv2WvQj.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "react": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react.QYXZqQxJ1j.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "react.QYXZqQxJ1j.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "react/jsx-runtime": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_jsx_runtime.RDhwXXoxCg.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "react_jsx_runtime.RDhwXXoxCg.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "react/jsx-dev-runtime": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_jsx_dev_runtime.UsMOGvdsKw.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "react_jsx_dev_runtime.UsMOGvdsKw.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "react-dom": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_dom.6SKyvL_ZIW.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "react_dom.6SKyvL_ZIW.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "react-dom/client": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_dom_client.lVKcx-4-HL.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "react_dom_client.lVKcx-4-HL.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "react-dom/profiling": {
          "dirty": false,
          "versions": [
            {
              "tag": "18.3.1",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "whiteboard",
                  "requiredVersion": "^18.3.1",
                  "strictVersion": true,
                  "file": "react_dom_profiling.wPFH8wjIJf.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "react_dom_profiling.wPFH8wjIJf.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "mermaid": {
          "dirty": false,
          "versions": [
            {
              "tag": "11.14.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mermaid",
                  "requiredVersion": "^11.4.1",
                  "strictVersion": true,
                  "file": "mermaid.fMI3T940QA.js",
                  "entries": null,
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "mermaid.fMI3T940QA.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/common": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_common.Ucn2BmyRM1.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_common",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_common.Ucn2BmyRM1.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/common/http": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_common_http.XnycUwbhpt.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_common",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_common_http.XnycUwbhpt.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/platform-browser": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_platform_browser.lAyP2N3Pw8.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_platform_browser",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_platform_browser.lAyP2N3Pw8.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "rxjs": {
          "dirty": false,
          "versions": [
            {
              "tag": "7.8.2",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "~7.8.0",
                  "strictVersion": true,
                  "file": "rxjs.IJzVNeB5rY.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-rxjs",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "rxjs.IJzVNeB5rY.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "rxjs/operators": {
          "dirty": false,
          "versions": [
            {
              "tag": "7.8.2",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "~7.8.0",
                  "strictVersion": true,
                  "file": "rxjs_operators.gdYSvUruih.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-rxjs",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "rxjs_operators.gdYSvUruih.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "tslib": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.8.1",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^2.3.0",
                  "strictVersion": true,
                  "file": "tslib.s6WVYyl__v.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-tslib",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "tslib.s6WVYyl__v.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/core": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core.RHjtWEkOzP.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_core",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_core.RHjtWEkOzP.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/core/event-dispatch-contract.min.js": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_core",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/di": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_primitives_di.QUc60-Xs6C.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_core",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_core_primitives_di.QUc60-Xs6C.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/event-dispatch": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_primitives_event_dispatch.1A9qBws3LP.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_core",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_core_primitives_event_dispatch.1A9qBws3LP.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/core/primitives/signals": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_primitives_signals.ePwPWbaXlE.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_core",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_core_primitives_signals.ePwPWbaXlE.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        },
        "@angular/core/rxjs-interop": {
          "dirty": false,
          "versions": [
            {
              "tag": "21.2.12",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^21.2.0",
                  "strictVersion": true,
                  "file": "_angular_core_rxjs_interop.YqevhcoUQy.js",
                  "entries": null,
                  "cached": true,
                  "bundle": "browser-angular_core",
                  "servedFiles": [
                    {
                      "entry": null,
                      "file": "_angular_core_rxjs_interop.YqevhcoUQy.js"
                    }
                  ],
                  "generation": "v4"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {
      "__NF-HOST__": {
        "browser-angular_common": [
          "chunk-WW26EZ22.js"
        ],
        "browser-rxjs": [
          "chunk-PAMKM67I.js"
        ],
        "browser-angular_core": [
          "chunk-RCIWTGS7.js",
          "chunk-K6ZMRNMW.js",
          "chunk-APTZXQMF.js",
          "chunk-V2SUVJ7R.js",
          "chunk-2VMXMS7J.js"
        ],
        "mapping-or-exposed": []
      }
    },
    "generation": "v4"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 22,
        "scopeCount": 1,
        "imports": [
          {
            "specifier": "@excalidraw/excalidraw",
            "target": "./whiteboard/_excalidraw_excalidraw.0MlOv2WvQj.js"
          },
          {
            "specifier": "react",
            "target": "./whiteboard/react.QYXZqQxJ1j.js"
          },
          {
            "specifier": "react/jsx-runtime",
            "target": "./whiteboard/react_jsx_runtime.RDhwXXoxCg.js"
          },
          {
            "specifier": "react/jsx-dev-runtime",
            "target": "./whiteboard/react_jsx_dev_runtime.UsMOGvdsKw.js"
          },
          {
            "specifier": "react-dom",
            "target": "./whiteboard/react_dom.6SKyvL_ZIW.js"
          },
          {
            "specifier": "react-dom/client",
            "target": "./whiteboard/react_dom_client.lVKcx-4-HL.js"
          },
          {
            "specifier": "react-dom/profiling",
            "target": "./whiteboard/react_dom_profiling.wPFH8wjIJf.js"
          },
          {
            "specifier": "mermaid",
            "target": "./mermaid/mermaid.fMI3T940QA.js"
          },
          {
            "specifier": "@angular/common",
            "target": "./_angular_common.Ucn2BmyRM1.js"
          },
          {
            "specifier": "@angular/common/http",
            "target": "./_angular_common_http.XnycUwbhpt.js"
          },
          {
            "specifier": "@angular/platform-browser",
            "target": "./_angular_platform_browser.lAyP2N3Pw8.js"
          },
          {
            "specifier": "rxjs",
            "target": "./rxjs.IJzVNeB5rY.js"
          },
          {
            "specifier": "rxjs/operators",
            "target": "./rxjs_operators.gdYSvUruih.js"
          },
          {
            "specifier": "tslib",
            "target": "./tslib.s6WVYyl__v.js"
          },
          {
            "specifier": "@angular/core",
            "target": "./_angular_core.RHjtWEkOzP.js"
          },
          {
            "specifier": "@angular/core/event-dispatch-contract.min.js",
            "target": "./_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js"
          },
          {
            "specifier": "@angular/core/primitives/di",
            "target": "./_angular_core_primitives_di.QUc60-Xs6C.js"
          },
          {
            "specifier": "@angular/core/primitives/event-dispatch",
            "target": "./_angular_core_primitives_event_dispatch.1A9qBws3LP.js"
          },
          {
            "specifier": "@angular/core/primitives/signals",
            "target": "./_angular_core_primitives_signals.ePwPWbaXlE.js"
          },
          {
            "specifier": "@angular/core/rxjs-interop",
            "target": "./_angular_core_rxjs_interop.YqevhcoUQy.js"
          },
          {
            "specifier": "whiteboard/./Bootstrap",
            "target": "./whiteboard/Bootstrap-7COJRA5I.js"
          },
          {
            "specifier": "mermaid/./Bootstrap",
            "target": "./mermaid/Bootstrap-BBNZEAEH.js"
          }
        ],
        "scopes": [
          {
            "scope": "./",
            "imports": [
              {
                "specifier": "@nf-internal/chunk-WW26EZ22",
                "target": "./chunk-WW26EZ22.js"
              },
              {
                "specifier": "@nf-internal/chunk-PAMKM67I",
                "target": "./chunk-PAMKM67I.js"
              },
              {
                "specifier": "@nf-internal/chunk-RCIWTGS7",
                "target": "./chunk-RCIWTGS7.js"
              },
              {
                "specifier": "@nf-internal/chunk-K6ZMRNMW",
                "target": "./chunk-K6ZMRNMW.js"
              },
              {
                "specifier": "@nf-internal/chunk-APTZXQMF",
                "target": "./chunk-APTZXQMF.js"
              },
              {
                "specifier": "@nf-internal/chunk-V2SUVJ7R",
                "target": "./chunk-V2SUVJ7R.js"
              },
              {
                "specifier": "@nf-internal/chunk-2VMXMS7J",
                "target": "./chunk-2VMXMS7J.js"
              }
            ]
          }
        ],
        "integrity": {
          "./whiteboard/_excalidraw_excalidraw.0MlOv2WvQj.js": "sha384-gQrm6C7mOLCTYcdQFNBrh7GZ3o5hy2K2NmxwOfiJtDzs7NTkKc5hTxSBfksuKbaU",
          "./whiteboard/react.QYXZqQxJ1j.js": "sha384-57khIiCnWo5tC9kEt0ibpdoHhHGtPXp1KmeWeJyyX0+UPwenA+Wj+0qvj7ajI3As",
          "./whiteboard/react_jsx_runtime.RDhwXXoxCg.js": "sha384-mWHwomGyGtSC45UesaeI3hV4diuzv10CMDSAWJ1rMRQ8F+lA71uneBirgsCW/JxO",
          "./whiteboard/react_jsx_dev_runtime.UsMOGvdsKw.js": "sha384-Pz3qELNqQbfKZe26gJ2n/S9ZKDnDcKoBB4HKdEphutzsxBeMedPySvP+iKitw5h/",
          "./whiteboard/react_dom.6SKyvL_ZIW.js": "sha384-P5wEc9b7LWwq+gIw6WZydAmGaqqKM9f1+8HOET0FxnhMqtpfCs6opvzQAXMtoyZA",
          "./whiteboard/react_dom_client.lVKcx-4-HL.js": "sha384-qhRGasTGrIXFNZJfwVfTnDA2+KKAGE/O6D+GEErqa6n/c3xiyVcKH1x4FmMqeUAN",
          "./whiteboard/react_dom_profiling.wPFH8wjIJf.js": "sha384-ljYfxwXdL20/jno4xQm1XDO5sL/8huAbZHNBeJ4Ov+nY5UDdOHl3ZwurHwevUCdI",
          "./mermaid/mermaid.fMI3T940QA.js": "sha384-kstnQo1tIfL+tMgIsAHgtN6HODg7IUJOB7YxDsvWEfQKwtm2T8pJXYurn7ZK8lW/",
          "./_angular_common.Ucn2BmyRM1.js": "sha384-ifIpCfW3pytDYCF1JasK/q29l9JcykVZmVSQPMbvfrIGyBjplklPOyLqxyHVtqL7",
          "./_angular_common_http.XnycUwbhpt.js": "sha384-IK8Nx+6NWCVROXYGp+8jufFYVZlMcU0/sA2pO54JMRAhwQCS6iZuRCEnwvAGIG0O",
          "./_angular_platform_browser.lAyP2N3Pw8.js": "sha384-Uqk4Pa50G3bzBAWwoZ0rCBacNLN2dyJ8QkJWL5QD6IqFLISZIk84SZzH8RmcXGlk",
          "./rxjs.IJzVNeB5rY.js": "sha384-CND2UMO83rk1q4PmwPBkMzMidBFPpleOKv8RwUTYv7MVKgLY5QZ4rSMNPkizOXfU",
          "./rxjs_operators.gdYSvUruih.js": "sha384-laChUqH6WQnng9RMXX09mNVUEHCCL/2hiynx8XKFxv8EpZDOXvUI6j2KJAvkz7/m",
          "./tslib.s6WVYyl__v.js": "sha384-us48hLnAuTVi42myNvtbK0UsmSvbAjKfiZP4HjtL9tB6FogW0rizxqZPIRAbidzm",
          "./_angular_core.RHjtWEkOzP.js": "sha384-K67ZQ5cbnDPIVn8WANbSD0mtv1yJTMx8mlSOumXJTrAgTrsuRNsDWfVtimzbGc8o",
          "./_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js": "sha384-5wVWeVYtx1cBT1jKmN8rQ7UM9OvfVXX8EiLwaa0Ske0MZEGspZWPPZzpPCmI7TvV",
          "./_angular_core_primitives_di.QUc60-Xs6C.js": "sha384-6rOmacKn8k2Rcgtrc+9Jiv4npsCyzrhos2r3DUvquC7Sy2zH1Qe8r7CLOIaKbfoP",
          "./_angular_core_primitives_event_dispatch.1A9qBws3LP.js": "sha384-MD1dEWUryHtZl1bJtQZQD2JHywLtf2noRB7QrVRtzO/zWxi/9bmM02zYvzWXySQM",
          "./_angular_core_primitives_signals.ePwPWbaXlE.js": "sha384-LPA4je4R4YerkZL5Dsogc8kPstf4JOzHn1RFaf8Pv5R+mNyYS3zwhgqy7LAAZePH",
          "./_angular_core_rxjs_interop.YqevhcoUQy.js": "sha384-ZmQah/VqzvO07m4LLHnI5ixj/1rxctq98QHEfgknKEma3JSgXejbnkph+m/WfWmc",
          "./whiteboard/Bootstrap-7COJRA5I.js": "sha384-7/Brmjo9gqN65lCvoMCfm1Ub5tyUw3ivabWA1NeC/UJOUrWzlfhIj0XYoFKiFEk7",
          "./mermaid/Bootstrap-BBNZEAEH.js": "sha384-DPpBRZv47CVBpYfzVQiKWL76+Zh+GNRvDSY7G99RMPT+j5U8Pq7eDciHllDgRaFO",
          "./chunk-WW26EZ22.js": "sha384-sDhcZ7eQ+i0rEfRIZ4dhGpwqqr4OLIKhrNr1CpqUuynnbsK2qpp/I/cq8JVcKfl0",
          "./chunk-PAMKM67I.js": "sha384-hTdulOFDbDpZPDXTPSqo9asD5kf/Rb2nqqOwqK/IzWWXyf8kf0+N94FSvSjPLKtF",
          "./chunk-RCIWTGS7.js": "sha384-GVoyZ7htW1QcYMK3i6Pio7FhoQCY+94M+cYKVVTZyrTUO6RQKqRpVu5T2ng478ha",
          "./chunk-K6ZMRNMW.js": "sha384-aZwtRvM310GrKNMB9tX07AS1Chpy7tOFkHUfDaJP+pAlU7dOs4PIXTpIFLeObnGV",
          "./chunk-APTZXQMF.js": "sha384-zWhh2apMCPktoaZjn6P/SeGHLy7ujJxm4zqpRZ0BLIciAD+DEHbQgnzCu06YN4vy",
          "./chunk-V2SUVJ7R.js": "sha384-BfAKYP5/8tfHP2fbRCyG4x5an/HWTuOKp4XtnZoJwWpXoctwT6gkvA4/b7qHWizn",
          "./chunk-2VMXMS7J.js": "sha384-IiJwn+tZf8TQkKyCcaAtb9JW90aZbS2eLcLYxvXmc4DKIkLJGSPoVR4c+hMZ/hi2"
        }
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@excalidraw/excalidraw",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/_excalidraw_excalidraw.0MlOv2WvQj.js"
        },
        {
          "specifier": "react",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react.QYXZqQxJ1j.js"
        },
        {
          "specifier": "react/jsx-runtime",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_jsx_runtime.RDhwXXoxCg.js"
        },
        {
          "specifier": "react/jsx-dev-runtime",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_jsx_dev_runtime.UsMOGvdsKw.js"
        },
        {
          "specifier": "react-dom",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_dom.6SKyvL_ZIW.js"
        },
        {
          "specifier": "react-dom/client",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_dom_client.lVKcx-4-HL.js"
        },
        {
          "specifier": "react-dom/profiling",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_dom_profiling.wPFH8wjIJf.js"
        },
        {
          "specifier": "mermaid",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/mermaid/mermaid.fMI3T940QA.js"
        },
        {
          "specifier": "@angular/common",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_common.Ucn2BmyRM1.js"
        },
        {
          "specifier": "@angular/common/http",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_common_http.XnycUwbhpt.js"
        },
        {
          "specifier": "@angular/platform-browser",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_platform_browser.lAyP2N3Pw8.js"
        },
        {
          "specifier": "rxjs",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/rxjs.IJzVNeB5rY.js"
        },
        {
          "specifier": "rxjs/operators",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/rxjs_operators.gdYSvUruih.js"
        },
        {
          "specifier": "tslib",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/tslib.s6WVYyl__v.js"
        },
        {
          "specifier": "@angular/core",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core.RHjtWEkOzP.js"
        },
        {
          "specifier": "@angular/core/event-dispatch-contract.min.js",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js"
        },
        {
          "specifier": "@angular/core/primitives/di",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_primitives_di.QUc60-Xs6C.js"
        },
        {
          "specifier": "@angular/core/primitives/event-dispatch",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_primitives_event_dispatch.1A9qBws3LP.js"
        },
        {
          "specifier": "@angular/core/primitives/signals",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_primitives_signals.ePwPWbaXlE.js"
        },
        {
          "specifier": "@angular/core/rxjs-interop",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_rxjs_interop.YqevhcoUQy.js"
        },
        {
          "specifier": "whiteboard/./Bootstrap",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/Bootstrap-7COJRA5I.js"
        },
        {
          "specifier": "mermaid/./Bootstrap",
          "target": "https://lutzleonhardt.de/frankenstein-meeting-room/mermaid/Bootstrap-BBNZEAEH.js"
        }
      ],
      "scopes": [
        {
          "scope": "https://lutzleonhardt.de/frankenstein-meeting-room/",
          "imports": [
            {
              "specifier": "@nf-internal/chunk-WW26EZ22",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-WW26EZ22.js"
            },
            {
              "specifier": "@nf-internal/chunk-PAMKM67I",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-PAMKM67I.js"
            },
            {
              "specifier": "@nf-internal/chunk-RCIWTGS7",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-RCIWTGS7.js"
            },
            {
              "specifier": "@nf-internal/chunk-K6ZMRNMW",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-K6ZMRNMW.js"
            },
            {
              "specifier": "@nf-internal/chunk-APTZXQMF",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-APTZXQMF.js"
            },
            {
              "specifier": "@nf-internal/chunk-V2SUVJ7R",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-V2SUVJ7R.js"
            },
            {
              "specifier": "@nf-internal/chunk-2VMXMS7J",
              "target": "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-2VMXMS7J.js"
            }
          ]
        }
      ],
      "integrityFor": [
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/_excalidraw_excalidraw.0MlOv2WvQj.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react.QYXZqQxJ1j.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_jsx_runtime.RDhwXXoxCg.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_jsx_dev_runtime.UsMOGvdsKw.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_dom.6SKyvL_ZIW.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_dom_client.lVKcx-4-HL.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/react_dom_profiling.wPFH8wjIJf.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/mermaid/mermaid.fMI3T940QA.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_common.Ucn2BmyRM1.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_common_http.XnycUwbhpt.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_platform_browser.lAyP2N3Pw8.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/rxjs.IJzVNeB5rY.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/rxjs_operators.gdYSvUruih.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/tslib.s6WVYyl__v.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core.RHjtWEkOzP.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_event_dispatch_contract_min_js.JotK85OfcE.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_primitives_di.QUc60-Xs6C.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_primitives_event_dispatch.1A9qBws3LP.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_primitives_signals.ePwPWbaXlE.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/_angular_core_rxjs_interop.YqevhcoUQy.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/whiteboard/Bootstrap-7COJRA5I.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/mermaid/Bootstrap-BBNZEAEH.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-WW26EZ22.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-PAMKM67I.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-RCIWTGS7.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-K6ZMRNMW.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-APTZXQMF.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-V2SUVJ7R.js",
        "https://lutzleonhardt.de/frankenstein-meeting-room/chunk-2VMXMS7J.js"
      ]
    }
  },
  "errors": []
};
