import { SnapshotV1 } from '../snapshot-v1';
import { cleanSkipFixture } from './clean-skip.fixture';
import { coDeclaredShareFixture } from './co-declared-share.fixture';
import { dynamicInitNativeFixture } from './dynamic-init-native.fixture';
import { dynamicInitShimFixture } from './dynamic-init-shim.fixture';
import { dynamicOverrideFixture } from './dynamic-override.fixture';
import { exportedPlaygroundCheckoutFixture } from './exported-playground-checkout.fixture';
import { frankensteinLiveFixture } from './frankenstein-live.fixture';
import { nonDenseFixture } from './non-dense.fixture';
import { poolingAnchorFixture } from './pooling-anchor.fixture';
import { scopeIsolationFixture } from './scope-isolation.fixture';
import { scopedFixture } from './scoped.fixture';
import { selfFillFixture } from './self-fill.fixture';
import { strictScopeFixture } from './strict-scope.fixture';
import { strictSplitFixture } from './strict-split.fixture';
import { syntheticCollisionFixture } from './synthetic-collision.fixture';
import { syntheticCustomNamespaceFixture } from './synthetic-custom-namespace.fixture';
import { syntheticCustomStorageFixture } from './synthetic-custom-storage.fixture';
import { syntheticDenseEntriesFixture } from './synthetic-dense-entries.fixture';
import { syntheticEmptyPageFixture } from './synthetic-empty-page.fixture';
import { syntheticHostileFixture } from './synthetic-hostile.fixture';
import { syntheticLegacySessionStorageFixture } from './synthetic-legacy-session-storage.fixture';
import { syntheticLocalStorageFixture } from './synthetic-local-storage.fixture';
import { syntheticMissingChannelFixture } from './synthetic-missing-channel.fixture';
import { syntheticMultiVersionFixture } from './synthetic-multi-version.fixture';
import { syntheticNoImportMapsFixture } from './synthetic-no-import-maps.fixture';
import { syntheticNotRecognizedFixture } from './synthetic-not-recognized.fixture';

/**
 * All checked-in fixtures. Ids equal the fixture file basenames
 * (`<id>.fixture.ts`) — the guards enforce this and scan every entry.
 *
 * The corpus-derived entries (one per lab scenario plus frankenstein-live)
 * are generated by `scripts/derive-fixtures.mjs` from the lossless capture
 * corpus under captures/; the synthetic entries are hand-written edge
 * states no real capture produces; the `exported-` entries are verbatim
 * SnapshotV1 panel exports of live pages (frozen evidence — no envelope,
 * outside the drift guard, never edited by hand).
 */
export const FIXTURES = {
  'frankenstein-live': frankensteinLiveFixture,
  'clean-skip': cleanSkipFixture,
  'co-declared-share': coDeclaredShareFixture,
  'dynamic-init-native': dynamicInitNativeFixture,
  'dynamic-init-shim': dynamicInitShimFixture,
  'dynamic-override': dynamicOverrideFixture,
  'exported-playground-checkout': exportedPlaygroundCheckoutFixture,
  'non-dense': nonDenseFixture,
  'pooling-anchor': poolingAnchorFixture,
  'scope-isolation': scopeIsolationFixture,
  scoped: scopedFixture,
  'self-fill': selfFillFixture,
  'strict-scope': strictScopeFixture,
  'strict-split': strictSplitFixture,
  'synthetic-collision': syntheticCollisionFixture,
  'synthetic-dense-entries': syntheticDenseEntriesFixture,
  'synthetic-hostile': syntheticHostileFixture,
  'synthetic-missing-channel': syntheticMissingChannelFixture,
  'synthetic-multi-version': syntheticMultiVersionFixture,
  'synthetic-no-import-maps': syntheticNoImportMapsFixture,
  'synthetic-not-recognized': syntheticNotRecognizedFixture,
  'synthetic-empty-page': syntheticEmptyPageFixture,
  'synthetic-local-storage': syntheticLocalStorageFixture,
  'synthetic-legacy-session-storage': syntheticLegacySessionStorageFixture,
  'synthetic-custom-namespace': syntheticCustomNamespaceFixture,
  'synthetic-custom-storage': syntheticCustomStorageFixture,
} satisfies Record<string, SnapshotV1>;

export type FixtureId = keyof typeof FIXTURES;

export const PRIMARY_FIXTURE_ID: FixtureId = 'frankenstein-live';
