import { SnapshotV1 } from '../snapshot-v1';
import { cleanSkipFixture } from './clean-skip.fixture';
import { coDeclaredShareFixture } from './co-declared-share.fixture';
import { denseBothFixture } from './dense-both.fixture';
import { denseChunkingOnlyFixture } from './dense-chunking-only.fixture';
import { denseExternalsOnlyFixture } from './dense-externals-only.fixture';
import { dynamicInitNativeFixture } from './dynamic-init-native.fixture';
import { dynamicInitShimFixture } from './dynamic-init-shim.fixture';
import { dynamicOverrideFixture } from './dynamic-override.fixture';
import { exportedPlaygroundCheckoutFixture } from './exported-playground-checkout.fixture';
import { frankensteinLiveFixture } from './frankenstein-live.fixture';
import { mergedEntrypointsFixture } from './merged-entrypoints.fixture';
import { multiScopeFixture } from './multi-scope.fixture';
import { nonDenseFixture } from './non-dense.fixture';
import { outOfRangeNonstrictFixture } from './out-of-range-nonstrict.fixture';
import { poolingAnchorFixture } from './pooling-anchor.fixture';
import { poolPortfolioFixture } from './pool-portfolio.fixture';
import { poolShowcaseFixture } from './pool-showcase.fixture';
import { poolTagAnchoredFixture } from './pool-tag-anchored.fixture';
import { poolTagCoherentFixture } from './pool-tag-coherent.fixture';
import { poolTagIslandedFixture } from './pool-tag-islanded.fixture';
import { poolTagOrphanFixture } from './pool-tag-orphan.fixture';
import { scopeIsolationFixture } from './scope-isolation.fixture';
import { scopedFixture } from './scoped.fixture';
import { selfFillFixture } from './self-fill.fixture';
import { strictScopeFixture } from './strict-scope.fixture';
import { strictSplitFixture } from './strict-split.fixture';
import { syntheticCollisionFixture } from './synthetic-collision.fixture';
import { syntheticDenseEntriesFixture } from './synthetic-dense-entries.fixture';
import { syntheticEmptyPageFixture } from './synthetic-empty-page.fixture';
import { syntheticHostileFixture } from './synthetic-hostile.fixture';
import { syntheticMissingChannelFixture } from './synthetic-missing-channel.fixture';
import { syntheticMultiVersionFixture } from './synthetic-multi-version.fixture';
import { syntheticNoImportMapsFixture } from './synthetic-no-import-maps.fixture';
import { syntheticNotRecognizedFixture } from './synthetic-not-recognized.fixture';
import { tornManyFixture } from './torn-many.fixture';

/**
 * All checked-in fixtures. Ids equal the fixture file basenames
 * (`<id>.fixture.ts`) — the guards enforce this and scan every entry.
 *
 * The corpus-derived entries (one per lab scenario plus frankenstein-live)
 * are generated by `scripts/derive-fixtures.mjs` from the lossless capture
 * corpus under captures/; the synthetic entries are hand-written edge
 * states no real capture produces; the `exported-` entries are verbatim
 * SnapshotV1 panel exports of live pages (frozen evidence — no envelope,
 * outside the drift guard, never edited by hand).
 */
export const FIXTURES = {
  'frankenstein-live': frankensteinLiveFixture,
  'clean-skip': cleanSkipFixture,
  'co-declared-share': coDeclaredShareFixture,
  'dense-both': denseBothFixture,
  'dense-chunking-only': denseChunkingOnlyFixture,
  'dense-externals-only': denseExternalsOnlyFixture,
  'dynamic-init-native': dynamicInitNativeFixture,
  'dynamic-init-shim': dynamicInitShimFixture,
  'dynamic-override': dynamicOverrideFixture,
  'exported-playground-checkout': exportedPlaygroundCheckoutFixture,
  'merged-entrypoints': mergedEntrypointsFixture,
  'multi-scope': multiScopeFixture,
  'non-dense': nonDenseFixture,
  'out-of-range-nonstrict': outOfRangeNonstrictFixture,
  'pooling-anchor': poolingAnchorFixture,
  'pool-portfolio': poolPortfolioFixture,
  'pool-showcase': poolShowcaseFixture,
  'pool-tag-anchored': poolTagAnchoredFixture,
  'pool-tag-coherent': poolTagCoherentFixture,
  'pool-tag-islanded': poolTagIslandedFixture,
  'pool-tag-orphan': poolTagOrphanFixture,
  'scope-isolation': scopeIsolationFixture,
  scoped: scopedFixture,
  'self-fill': selfFillFixture,
  'strict-scope': strictScopeFixture,
  'strict-split': strictSplitFixture,
  'torn-many': tornManyFixture,
  'synthetic-collision': syntheticCollisionFixture,
  'synthetic-dense-entries': syntheticDenseEntriesFixture,
  'synthetic-hostile': syntheticHostileFixture,
  'synthetic-missing-channel': syntheticMissingChannelFixture,
  'synthetic-multi-version': syntheticMultiVersionFixture,
  'synthetic-no-import-maps': syntheticNoImportMapsFixture,
  'synthetic-not-recognized': syntheticNotRecognizedFixture,
  'synthetic-empty-page': syntheticEmptyPageFixture,
} satisfies Record<string, SnapshotV1>;

export type FixtureId = keyof typeof FIXTURES;

export const PRIMARY_FIXTURE_ID: FixtureId = 'frankenstein-live';
