// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/merged-entrypoints/20261001T164530Z.json (corpus run 20261001T164530Z),
// envelope lab-lossless-capture/1, orchestrator v4.7.0, observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const mergedEntrypointsFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-10-01T16:45:32.807Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/3"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-374BJDUE.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/kit": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.2.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.DSYCipaGyy.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.DSYCipaGyy.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "mfe1",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.DSYCipaGyy.js",
                    "@nf-lab/kit/table": "_nf_lab_kit_table.B_lIn12dNZ.js",
                    "@nf-lab/kit/dialog": "_nf_lab_kit_dialog.P5E_5ASKB7.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.DSYCipaGyy.js"
                    },
                    {
                      "entry": "@nf-lab/kit/table",
                      "file": "_nf_lab_kit_table.B_lIn12dNZ.js"
                    },
                    {
                      "entry": "@nf-lab/kit/dialog",
                      "file": "_nf_lab_kit_dialog.P5E_5ASKB7.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {},
    "generation": "v4.5",
    "orchestratorVersion": "4.7.0"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 4,
        "scopeCount": 0,
        "imports": [
          {
            "specifier": "@nf-lab/kit",
            "target": "./_nf_lab_kit.DSYCipaGyy.js"
          },
          {
            "specifier": "@nf-lab/kit/table",
            "target": "./mfe1/_nf_lab_kit_table.B_lIn12dNZ.js"
          },
          {
            "specifier": "@nf-lab/kit/dialog",
            "target": "./mfe1/_nf_lab_kit_dialog.P5E_5ASKB7.js"
          },
          {
            "specifier": "mfe1/./main",
            "target": "./mfe1/main-374BJDUE.js"
          }
        ],
        "scopes": [],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/kit",
          "target": "http://localhost:4300/_nf_lab_kit.DSYCipaGyy.js"
        },
        {
          "specifier": "@nf-lab/kit/table",
          "target": "http://localhost:4300/mfe1/_nf_lab_kit_table.B_lIn12dNZ.js"
        },
        {
          "specifier": "@nf-lab/kit/dialog",
          "target": "http://localhost:4300/mfe1/_nf_lab_kit_dialog.P5E_5ASKB7.js"
        },
        {
          "specifier": "mfe1/./main",
          "target": "http://localhost:4300/mfe1/main-374BJDUE.js"
        }
      ],
      "scopes": [],
      "integrityFor": []
    }
  },
  "errors": []
};
