// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/multi-scope/20261001T164530Z.json (corpus run 20261001T164530Z),
// envelope lab-lossless-capture/1, orchestrator v4.7.0, observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const multiScopeFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-10-01T16:45:38.979Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/3"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-I2IWCNAM.js"
          }
        ],
        "integrity": {}
      },
      "mfe2": {
        "scopeUrl": "./mfe2/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-I2IWCNAM.js"
          }
        ],
        "integrity": {}
      },
      "mfe3": {
        "scopeUrl": "./mfe3/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-I2IWCNAM.js"
          }
        ],
        "integrity": {}
      },
      "mfe4": {
        "scopeUrl": "./mfe4/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-I2IWCNAM.js"
          }
        ],
        "integrity": {}
      },
      "mfe5": {
        "scopeUrl": "./mfe5/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-I2IWCNAM.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/kit": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.4.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.L63SrDXJGr.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.L63SrDXJGr.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.2.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.DSYCipaGyy.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.DSYCipaGyy.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      },
      "team-a": {
        "@nf-lab/kit": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.3.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe2",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.1IDRTBdr7s.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.1IDRTBdr7s.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.2.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "mfe3",
                  "requiredVersion": "^1.2.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.DSYCipaGyy.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.DSYCipaGyy.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      },
      "strict": {
        "@nf-lab/kit": {
          "dirty": false,
          "versions": [
            {
              "tag": "2.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe4",
                  "requiredVersion": "2.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.6ezSr-plfZ.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.6ezSr-plfZ.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.3.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe5",
                  "requiredVersion": "1.3.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/kit": "_nf_lab_kit.1IDRTBdr7s.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/kit",
                      "file": "_nf_lab_kit.1IDRTBdr7s.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {},
    "generation": "v4.5",
    "orchestratorVersion": "4.7.0"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 6,
        "scopeCount": 4,
        "imports": [
          {
            "specifier": "@nf-lab/kit",
            "target": "./_nf_lab_kit.L63SrDXJGr.js"
          },
          {
            "specifier": "mfe1/./main",
            "target": "./mfe1/main-I2IWCNAM.js"
          },
          {
            "specifier": "mfe2/./main",
            "target": "./mfe2/main-I2IWCNAM.js"
          },
          {
            "specifier": "mfe3/./main",
            "target": "./mfe3/main-I2IWCNAM.js"
          },
          {
            "specifier": "mfe4/./main",
            "target": "./mfe4/main-I2IWCNAM.js"
          },
          {
            "specifier": "mfe5/./main",
            "target": "./mfe5/main-I2IWCNAM.js"
          }
        ],
        "scopes": [
          {
            "scope": "./mfe2/",
            "imports": [
              {
                "specifier": "@nf-lab/kit",
                "target": "./mfe2/_nf_lab_kit.1IDRTBdr7s.js"
              }
            ]
          },
          {
            "scope": "./mfe3/",
            "imports": [
              {
                "specifier": "@nf-lab/kit",
                "target": "./mfe2/_nf_lab_kit.1IDRTBdr7s.js"
              }
            ]
          },
          {
            "scope": "./mfe4/",
            "imports": [
              {
                "specifier": "@nf-lab/kit",
                "target": "./mfe4/_nf_lab_kit.6ezSr-plfZ.js"
              }
            ]
          },
          {
            "scope": "./mfe5/",
            "imports": [
              {
                "specifier": "@nf-lab/kit",
                "target": "./mfe5/_nf_lab_kit.1IDRTBdr7s.js"
              }
            ]
          }
        ],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/kit",
          "target": "http://localhost:4300/_nf_lab_kit.L63SrDXJGr.js"
        },
        {
          "specifier": "mfe1/./main",
          "target": "http://localhost:4300/mfe1/main-I2IWCNAM.js"
        },
        {
          "specifier": "mfe2/./main",
          "target": "http://localhost:4300/mfe2/main-I2IWCNAM.js"
        },
        {
          "specifier": "mfe3/./main",
          "target": "http://localhost:4300/mfe3/main-I2IWCNAM.js"
        },
        {
          "specifier": "mfe4/./main",
          "target": "http://localhost:4300/mfe4/main-I2IWCNAM.js"
        },
        {
          "specifier": "mfe5/./main",
          "target": "http://localhost:4300/mfe5/main-I2IWCNAM.js"
        }
      ],
      "scopes": [
        {
          "scope": "http://localhost:4300/mfe2/",
          "imports": [
            {
              "specifier": "@nf-lab/kit",
              "target": "http://localhost:4300/mfe2/_nf_lab_kit.1IDRTBdr7s.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/mfe3/",
          "imports": [
            {
              "specifier": "@nf-lab/kit",
              "target": "http://localhost:4300/mfe2/_nf_lab_kit.1IDRTBdr7s.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/mfe4/",
          "imports": [
            {
              "specifier": "@nf-lab/kit",
              "target": "http://localhost:4300/mfe4/_nf_lab_kit.6ezSr-plfZ.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/mfe5/",
          "imports": [
            {
              "specifier": "@nf-lab/kit",
              "target": "http://localhost:4300/mfe5/_nf_lab_kit.1IDRTBdr7s.js"
            }
          ]
        }
      ],
      "integrityFor": []
    }
  },
  "errors": []
};
