// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/pool-showcase/20260930T113012Z.json (corpus run 20260930T113012Z),
// envelope lab-lossless-capture/1, orchestrator v4.7.0, observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const poolShowcaseFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-09-30T11:30:48.031Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/3"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "catalog": {
        "scopeUrl": "./catalog/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-PQZ5SSMN.js"
          }
        ],
        "integrity": {}
      },
      "checkout": {
        "scopeUrl": "./checkout/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-ZDNE25RO.js"
          }
        ],
        "integrity": {}
      },
      "dashboard": {
        "scopeUrl": "./dashboard/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-TNGFKWTS.js"
          }
        ],
        "integrity": {}
      },
      "admin": {
        "scopeUrl": "./admin/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-DXLIHA7T.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/ui-core": {
          "dirty": false,
          "poolName": "ui",
          "versions": [
            {
              "tag": "2.0.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.jpfHqL1p12.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.jpfHqL1p12.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "catalog",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.FGCSlTph3q.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "ui",
                  "servedBy": "catalog",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.FGCSlTph3q.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "checkout",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.FGCSlTph3q.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "ui",
                  "servedBy": "catalog",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.FGCSlTph3q.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "admin",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.FGCSlTph3q.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedBy": "catalog",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.FGCSlTph3q.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/ui-dom": {
          "dirty": false,
          "poolName": "ui",
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "catalog",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-dom": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "ui",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-dom",
                      "file": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "checkout",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-dom": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "ui",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-dom",
                      "file": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "admin",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-dom": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-dom",
                      "file": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/chart-core": {
          "dirty": false,
          "poolName": "charts",
          "versions": [
            {
              "tag": "1.1.0",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "catalog",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/chart-core": "_nf_lab_chart_core.QRSGk-3c7N.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "charts",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/chart-core",
                      "file": "_nf_lab_chart_core.QRSGk-3c7N.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "dashboard",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/chart-core": "_nf_lab_chart_core.euTvcmIiPr.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "charts",
                  "poolCause": "unshared",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/chart-core",
                      "file": "_nf_lab_chart_core.euTvcmIiPr.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/chart-dom": {
          "dirty": false,
          "poolName": "charts",
          "versions": [
            {
              "tag": "2.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "dashboard",
                  "requiredVersion": "^2.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/chart-dom": "_nf_lab_chart_dom.6_R0EKaJeR.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "charts",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/chart-dom",
                      "file": "_nf_lab_chart_dom.6_R0EKaJeR.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.1.0",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "catalog",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/chart-dom": "_nf_lab_chart_dom.SA3JviWrvM.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "charts",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/chart-dom",
                      "file": "_nf_lab_chart_dom.SA3JviWrvM.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/icons": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "catalog",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/icons": "_nf_lab_icons.uMxgeSlPRR.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "icons",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/icons",
                      "file": "_nf_lab_icons.uMxgeSlPRR.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/form-core": {
          "dirty": false,
          "poolName": "form-kit",
          "versions": [
            {
              "tag": "1.1.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "checkout",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/form-core": "_nf_lab_form_core.1pzqm5CgNE.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "forms",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/form-core",
                      "file": "_nf_lab_form_core.1pzqm5CgNE.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "dashboard",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/form-core": "_nf_lab_form_core.Ftjrfi-4II.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "form-kit",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/form-core",
                      "file": "_nf_lab_form_core.Ftjrfi-4II.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/form-dom": {
          "dirty": false,
          "poolName": "form-kit",
          "versions": [
            {
              "tag": "1.1.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "checkout",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/form-dom": "_nf_lab_form_dom.inoBQwtA8E.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "forms",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/form-dom",
                      "file": "_nf_lab_form_dom.inoBQwtA8E.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "dashboard",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/form-dom": "_nf_lab_form_dom.kW_oSnirh8.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "form-kit",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/form-dom",
                      "file": "_nf_lab_form_dom.kW_oSnirh8.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/utils": {
          "dirty": false,
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^1.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/utils": "_nf_lab_utils.wMYw37SmBF.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/utils",
                      "file": "_nf_lab_utils.wMYw37SmBF.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {},
    "generation": "v4.5",
    "orchestratorVersion": "4.7.0"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 11,
        "scopeCount": 4,
        "imports": [
          {
            "specifier": "@nf-lab/ui-core",
            "target": "./_nf_lab_ui_core.jpfHqL1p12.js"
          },
          {
            "specifier": "@nf-lab/ui-dom",
            "target": "./catalog/_nf_lab_ui_dom.LEdXNkv1m2.js"
          },
          {
            "specifier": "@nf-lab/chart-dom",
            "target": "./dashboard/_nf_lab_chart_dom.6_R0EKaJeR.js"
          },
          {
            "specifier": "@nf-lab/icons",
            "target": "./catalog/_nf_lab_icons.uMxgeSlPRR.js"
          },
          {
            "specifier": "@nf-lab/form-core",
            "target": "./checkout/_nf_lab_form_core.1pzqm5CgNE.js"
          },
          {
            "specifier": "@nf-lab/form-dom",
            "target": "./checkout/_nf_lab_form_dom.inoBQwtA8E.js"
          },
          {
            "specifier": "@nf-lab/utils",
            "target": "./_nf_lab_utils.wMYw37SmBF.js"
          },
          {
            "specifier": "catalog/./main",
            "target": "./catalog/main-PQZ5SSMN.js"
          },
          {
            "specifier": "checkout/./main",
            "target": "./checkout/main-ZDNE25RO.js"
          },
          {
            "specifier": "dashboard/./main",
            "target": "./dashboard/main-TNGFKWTS.js"
          },
          {
            "specifier": "admin/./main",
            "target": "./admin/main-DXLIHA7T.js"
          }
        ],
        "scopes": [
          {
            "scope": "./catalog/",
            "imports": [
              {
                "specifier": "@nf-lab/chart-core",
                "target": "./catalog/_nf_lab_chart_core.QRSGk-3c7N.js"
              },
              {
                "specifier": "@nf-lab/chart-dom",
                "target": "./catalog/_nf_lab_chart_dom.SA3JviWrvM.js"
              },
              {
                "specifier": "@nf-lab/ui-core",
                "target": "./catalog/_nf_lab_ui_core.FGCSlTph3q.js"
              }
            ]
          },
          {
            "scope": "./dashboard/",
            "imports": [
              {
                "specifier": "@nf-lab/chart-core",
                "target": "./dashboard/_nf_lab_chart_core.euTvcmIiPr.js"
              }
            ]
          },
          {
            "scope": "./checkout/",
            "imports": [
              {
                "specifier": "@nf-lab/ui-core",
                "target": "./catalog/_nf_lab_ui_core.FGCSlTph3q.js"
              }
            ]
          },
          {
            "scope": "./admin/",
            "imports": [
              {
                "specifier": "@nf-lab/ui-core",
                "target": "./catalog/_nf_lab_ui_core.FGCSlTph3q.js"
              }
            ]
          }
        ],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/ui-core",
          "target": "http://localhost:4300/_nf_lab_ui_core.jpfHqL1p12.js"
        },
        {
          "specifier": "@nf-lab/ui-dom",
          "target": "http://localhost:4300/catalog/_nf_lab_ui_dom.LEdXNkv1m2.js"
        },
        {
          "specifier": "@nf-lab/chart-dom",
          "target": "http://localhost:4300/dashboard/_nf_lab_chart_dom.6_R0EKaJeR.js"
        },
        {
          "specifier": "@nf-lab/icons",
          "target": "http://localhost:4300/catalog/_nf_lab_icons.uMxgeSlPRR.js"
        },
        {
          "specifier": "@nf-lab/form-core",
          "target": "http://localhost:4300/checkout/_nf_lab_form_core.1pzqm5CgNE.js"
        },
        {
          "specifier": "@nf-lab/form-dom",
          "target": "http://localhost:4300/checkout/_nf_lab_form_dom.inoBQwtA8E.js"
        },
        {
          "specifier": "@nf-lab/utils",
          "target": "http://localhost:4300/_nf_lab_utils.wMYw37SmBF.js"
        },
        {
          "specifier": "catalog/./main",
          "target": "http://localhost:4300/catalog/main-PQZ5SSMN.js"
        },
        {
          "specifier": "checkout/./main",
          "target": "http://localhost:4300/checkout/main-ZDNE25RO.js"
        },
        {
          "specifier": "dashboard/./main",
          "target": "http://localhost:4300/dashboard/main-TNGFKWTS.js"
        },
        {
          "specifier": "admin/./main",
          "target": "http://localhost:4300/admin/main-DXLIHA7T.js"
        }
      ],
      "scopes": [
        {
          "scope": "http://localhost:4300/catalog/",
          "imports": [
            {
              "specifier": "@nf-lab/chart-core",
              "target": "http://localhost:4300/catalog/_nf_lab_chart_core.QRSGk-3c7N.js"
            },
            {
              "specifier": "@nf-lab/chart-dom",
              "target": "http://localhost:4300/catalog/_nf_lab_chart_dom.SA3JviWrvM.js"
            },
            {
              "specifier": "@nf-lab/ui-core",
              "target": "http://localhost:4300/catalog/_nf_lab_ui_core.FGCSlTph3q.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/dashboard/",
          "imports": [
            {
              "specifier": "@nf-lab/chart-core",
              "target": "http://localhost:4300/dashboard/_nf_lab_chart_core.euTvcmIiPr.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/checkout/",
          "imports": [
            {
              "specifier": "@nf-lab/ui-core",
              "target": "http://localhost:4300/catalog/_nf_lab_ui_core.FGCSlTph3q.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/admin/",
          "imports": [
            {
              "specifier": "@nf-lab/ui-core",
              "target": "http://localhost:4300/catalog/_nf_lab_ui_core.FGCSlTph3q.js"
            }
          ]
        }
      ],
      "integrityFor": []
    }
  },
  "errors": []
};
