// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/pool-tag-anchored/20260930T113012Z.json (corpus run 20260930T113012Z),
// envelope lab-lossless-capture/1, orchestrator v4.7.0, observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const poolTagAnchoredFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-09-30T11:30:53.380Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/3"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "mfe1": {
        "scopeUrl": "./mfe1/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-DXLIHA7T.js"
          }
        ],
        "integrity": {}
      },
      "mfe2": {
        "scopeUrl": "./mfe2/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-DXLIHA7T.js"
          }
        ],
        "integrity": {}
      },
      "mfe3": {
        "scopeUrl": "./mfe3/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-DXLIHA7T.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/ui-core": {
          "dirty": false,
          "poolName": "ui",
          "versions": [
            {
              "tag": "2.0.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.jpfHqL1p12.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.jpfHqL1p12.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "1.0.0",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.FGCSlTph3q.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "ui",
                  "servedBy": "mfe1",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.FGCSlTph3q.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "mfe2",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.FGCSlTph3q.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "ui",
                  "servedBy": "mfe1",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.FGCSlTph3q.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "mfe3",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-core": "_nf_lab_ui_core.FGCSlTph3q.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedBy": "mfe1",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-core",
                      "file": "_nf_lab_ui_core.FGCSlTph3q.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/ui-dom": {
          "dirty": false,
          "poolName": "ui",
          "versions": [
            {
              "tag": "1.0.0",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "mfe1",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-dom": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "ui",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-dom",
                      "file": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "mfe2",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-dom": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "ui",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-dom",
                      "file": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "mfe3",
                  "requiredVersion": ">=1.0.0 <3.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/ui-dom": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/ui-dom",
                      "file": "_nf_lab_ui_dom.LEdXNkv1m2.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {},
    "generation": "v4.5",
    "orchestratorVersion": "4.7.0"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 5,
        "scopeCount": 3,
        "imports": [
          {
            "specifier": "@nf-lab/ui-core",
            "target": "./_nf_lab_ui_core.jpfHqL1p12.js"
          },
          {
            "specifier": "@nf-lab/ui-dom",
            "target": "./mfe1/_nf_lab_ui_dom.LEdXNkv1m2.js"
          },
          {
            "specifier": "mfe1/./main",
            "target": "./mfe1/main-DXLIHA7T.js"
          },
          {
            "specifier": "mfe2/./main",
            "target": "./mfe2/main-DXLIHA7T.js"
          },
          {
            "specifier": "mfe3/./main",
            "target": "./mfe3/main-DXLIHA7T.js"
          }
        ],
        "scopes": [
          {
            "scope": "./mfe1/",
            "imports": [
              {
                "specifier": "@nf-lab/ui-core",
                "target": "./mfe1/_nf_lab_ui_core.FGCSlTph3q.js"
              }
            ]
          },
          {
            "scope": "./mfe2/",
            "imports": [
              {
                "specifier": "@nf-lab/ui-core",
                "target": "./mfe1/_nf_lab_ui_core.FGCSlTph3q.js"
              }
            ]
          },
          {
            "scope": "./mfe3/",
            "imports": [
              {
                "specifier": "@nf-lab/ui-core",
                "target": "./mfe1/_nf_lab_ui_core.FGCSlTph3q.js"
              }
            ]
          }
        ],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/ui-core",
          "target": "http://localhost:4300/_nf_lab_ui_core.jpfHqL1p12.js"
        },
        {
          "specifier": "@nf-lab/ui-dom",
          "target": "http://localhost:4300/mfe1/_nf_lab_ui_dom.LEdXNkv1m2.js"
        },
        {
          "specifier": "mfe1/./main",
          "target": "http://localhost:4300/mfe1/main-DXLIHA7T.js"
        },
        {
          "specifier": "mfe2/./main",
          "target": "http://localhost:4300/mfe2/main-DXLIHA7T.js"
        },
        {
          "specifier": "mfe3/./main",
          "target": "http://localhost:4300/mfe3/main-DXLIHA7T.js"
        }
      ],
      "scopes": [
        {
          "scope": "http://localhost:4300/mfe1/",
          "imports": [
            {
              "specifier": "@nf-lab/ui-core",
              "target": "http://localhost:4300/mfe1/_nf_lab_ui_core.FGCSlTph3q.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/mfe2/",
          "imports": [
            {
              "specifier": "@nf-lab/ui-core",
              "target": "http://localhost:4300/mfe1/_nf_lab_ui_core.FGCSlTph3q.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/mfe3/",
          "imports": [
            {
              "specifier": "@nf-lab/ui-core",
              "target": "http://localhost:4300/mfe1/_nf_lab_ui_core.FGCSlTph3q.js"
            }
          ]
        }
      ],
      "integrityFor": []
    }
  },
  "errors": []
};
