// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.
// Source: captures/pool-portfolio/20260930T113012Z.json (corpus run 20260930T113012Z),
// envelope lab-lossless-capture/1, orchestrator v4.7.0, observed
// generation: v4.5 — see captures/README.md for provenance.
// Derived through the real collector pipeline (capture-seeded page → probe
// eval → mapProbeResult), so the fixture equals pipeline output by construction.

import { SnapshotV1 } from '../snapshot-v1';

export const poolPortfolioFixture: SnapshotV1 = {
  "schemaVersion": 1,
  "capture": {
    "pageUrl": "http://localhost:4300/",
    "capturedAt": "2026-09-30T11:30:40.897Z",
    "mode": "passive",
    "collectorVersion": "nf-devtools-collector/3"
  },
  "channels": {
    "nativeFederationGlobals": {
      "state": "available"
    },
    "domImportMaps": {
      "state": "available"
    },
    "importShim": {
      "state": "available"
    }
  },
  "runtime": {
    "remotes": {
      "products": {
        "scopeUrl": "./products/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-JZC7PVTU.js"
          }
        ],
        "integrity": {}
      },
      "search": {
        "scopeUrl": "./search/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-JZC7PVTU.js"
          }
        ],
        "integrity": {}
      },
      "settings": {
        "scopeUrl": "./settings/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-JZC7PVTU.js"
          }
        ],
        "integrity": {}
      },
      "profile": {
        "scopeUrl": "./profile/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-JZC7PVTU.js"
          }
        ],
        "integrity": {}
      },
      "cart": {
        "scopeUrl": "./cart/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-JZC7PVTU.js"
          }
        ],
        "integrity": {}
      },
      "orders": {
        "scopeUrl": "./orders/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SJMAHDUI.js"
          }
        ],
        "integrity": {}
      },
      "invoices": {
        "scopeUrl": "./invoices/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SJMAHDUI.js"
          }
        ],
        "integrity": {}
      },
      "contacts": {
        "scopeUrl": "./contacts/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SJMAHDUI.js"
          }
        ],
        "integrity": {}
      },
      "onboarding": {
        "scopeUrl": "./onboarding/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SJMAHDUI.js"
          }
        ],
        "integrity": {}
      },
      "reports": {
        "scopeUrl": "./reports/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SJMAHDUI.js"
          }
        ],
        "integrity": {}
      },
      "legacy": {
        "scopeUrl": "./legacy/",
        "exposes": [
          {
            "moduleName": "./main",
            "file": "main-SJMAHDUI.js"
          }
        ],
        "integrity": {}
      },
      "__NF-HOST__": {
        "scopeUrl": "./",
        "exposes": [],
        "integrity": {}
      }
    },
    "scopedExternals": {},
    "sharedExternals": {
      "__GLOBAL__": {
        "@nf-lab/acme-core": {
          "dirty": false,
          "poolName": "acme",
          "versions": [
            {
              "tag": "18.2.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core._lqn63yOi7.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core._lqn63yOi7.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "18.1.3",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "products",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "search",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "settings",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "profile",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "cart",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "orders",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "invoices",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "contacts",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "onboarding",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "reports",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.CBL6eVZ92m.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.CBL6eVZ92m.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "16.2.12",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "legacy",
                  "requiredVersion": "^16.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-core": "_nf_lab_acme_core.9F39ycxW9d.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-core",
                      "file": "_nf_lab_acme_core.9F39ycxW9d.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/acme-common": {
          "dirty": false,
          "poolName": "acme",
          "versions": [
            {
              "tag": "18.2.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.MmYG9ya5tm.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.MmYG9ya5tm.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "18.1.3",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "products",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "search",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "settings",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "profile",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "cart",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "orders",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "invoices",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "contacts",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "onboarding",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "reports",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.xj02f30kez.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.xj02f30kez.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "16.2.12",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "legacy",
                  "requiredVersion": "^16.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-common": "_nf_lab_acme_common.zpK1ykCNPu.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-common",
                      "file": "_nf_lab_acme_common.zpK1ykCNPu.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/acme-router": {
          "dirty": false,
          "poolName": "acme",
          "versions": [
            {
              "tag": "18.2.0",
              "action": "share",
              "host": true,
              "remotes": [
                {
                  "name": "__NF-HOST__",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.0upHOBLkHx.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.0upHOBLkHx.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "18.1.3",
              "action": "skip",
              "host": false,
              "remotes": [
                {
                  "name": "products",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "search",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "settings",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "profile",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "cart",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "orders",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "invoices",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "contacts",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "onboarding",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "reports",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.LZMoTvZiG2.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedBy": "orders",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.LZMoTvZiG2.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "16.2.12",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "legacy",
                  "requiredVersion": "^16.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-router": "_nf_lab_acme_router.AwUyup05cP.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-router",
                      "file": "_nf_lab_acme_router.AwUyup05cP.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/acme-forms": {
          "dirty": false,
          "poolName": "acme",
          "versions": [
            {
              "tag": "18.1.3",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "orders",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-forms": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-forms",
                      "file": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "invoices",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-forms": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-forms",
                      "file": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "contacts",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-forms": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-forms",
                      "file": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "onboarding",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-forms": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-forms",
                      "file": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "reports",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-forms": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-forms",
                      "file": "_nf_lab_acme_forms.IWzwv3bFmd.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "16.2.12",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "legacy",
                  "requiredVersion": "^16.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-forms": "_nf_lab_acme_forms.94Pg3JRWsX.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-forms",
                      "file": "_nf_lab_acme_forms.94Pg3JRWsX.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        },
        "@nf-lab/acme-animations": {
          "dirty": false,
          "poolName": "acme",
          "versions": [
            {
              "tag": "18.1.3",
              "action": "share",
              "host": false,
              "remotes": [
                {
                  "name": "orders",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-animations": "_nf_lab_acme_animations.iX1JyydcgC.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-animations",
                      "file": "_nf_lab_acme_animations.iX1JyydcgC.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "invoices",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-animations": "_nf_lab_acme_animations.iX1JyydcgC.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-animations",
                      "file": "_nf_lab_acme_animations.iX1JyydcgC.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "contacts",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-animations": "_nf_lab_acme_animations.iX1JyydcgC.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-animations",
                      "file": "_nf_lab_acme_animations.iX1JyydcgC.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "onboarding",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-animations": "_nf_lab_acme_animations.iX1JyydcgC.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "pool": "acme",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-animations",
                      "file": "_nf_lab_acme_animations.iX1JyydcgC.js"
                    }
                  ],
                  "generation": "v4.5"
                },
                {
                  "name": "reports",
                  "requiredVersion": "^18.0.0",
                  "strictVersion": true,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-animations": "_nf_lab_acme_animations.iX1JyydcgC.js"
                  },
                  "cached": false,
                  "bundle": null,
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-animations",
                      "file": "_nf_lab_acme_animations.iX1JyydcgC.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            },
            {
              "tag": "16.2.12",
              "action": "scope",
              "host": false,
              "remotes": [
                {
                  "name": "legacy",
                  "requiredVersion": "^16.0.0",
                  "strictVersion": false,
                  "file": null,
                  "entries": {
                    "@nf-lab/acme-animations": "_nf_lab_acme_animations.3hwm9OyNIq.js"
                  },
                  "cached": true,
                  "bundle": null,
                  "pool": "acme",
                  "poolCause": "incompatible",
                  "servedFiles": [
                    {
                      "entry": "@nf-lab/acme-animations",
                      "file": "_nf_lab_acme_animations.3hwm9OyNIq.js"
                    }
                  ],
                  "generation": "v4.5"
                }
              ]
            }
          ]
        }
      }
    },
    "sharedChunks": {},
    "generation": "v4.5",
    "orchestratorVersion": "4.7.0"
  },
  "importMaps": {
    "documentMaps": [
      {
        "kind": "importmap-shim",
        "parsed": true,
        "importCount": 16,
        "scopeCount": 6,
        "imports": [
          {
            "specifier": "@nf-lab/acme-core",
            "target": "./_nf_lab_acme_core._lqn63yOi7.js"
          },
          {
            "specifier": "@nf-lab/acme-common",
            "target": "./_nf_lab_acme_common.MmYG9ya5tm.js"
          },
          {
            "specifier": "@nf-lab/acme-router",
            "target": "./_nf_lab_acme_router.0upHOBLkHx.js"
          },
          {
            "specifier": "@nf-lab/acme-forms",
            "target": "./orders/_nf_lab_acme_forms.IWzwv3bFmd.js"
          },
          {
            "specifier": "@nf-lab/acme-animations",
            "target": "./orders/_nf_lab_acme_animations.iX1JyydcgC.js"
          },
          {
            "specifier": "products/./main",
            "target": "./products/main-JZC7PVTU.js"
          },
          {
            "specifier": "search/./main",
            "target": "./search/main-JZC7PVTU.js"
          },
          {
            "specifier": "settings/./main",
            "target": "./settings/main-JZC7PVTU.js"
          },
          {
            "specifier": "profile/./main",
            "target": "./profile/main-JZC7PVTU.js"
          },
          {
            "specifier": "cart/./main",
            "target": "./cart/main-JZC7PVTU.js"
          },
          {
            "specifier": "orders/./main",
            "target": "./orders/main-SJMAHDUI.js"
          },
          {
            "specifier": "invoices/./main",
            "target": "./invoices/main-SJMAHDUI.js"
          },
          {
            "specifier": "contacts/./main",
            "target": "./contacts/main-SJMAHDUI.js"
          },
          {
            "specifier": "onboarding/./main",
            "target": "./onboarding/main-SJMAHDUI.js"
          },
          {
            "specifier": "reports/./main",
            "target": "./reports/main-SJMAHDUI.js"
          },
          {
            "specifier": "legacy/./main",
            "target": "./legacy/main-SJMAHDUI.js"
          }
        ],
        "scopes": [
          {
            "scope": "./legacy/",
            "imports": [
              {
                "specifier": "@nf-lab/acme-core",
                "target": "./legacy/_nf_lab_acme_core.9F39ycxW9d.js"
              },
              {
                "specifier": "@nf-lab/acme-common",
                "target": "./legacy/_nf_lab_acme_common.zpK1ykCNPu.js"
              },
              {
                "specifier": "@nf-lab/acme-router",
                "target": "./legacy/_nf_lab_acme_router.AwUyup05cP.js"
              },
              {
                "specifier": "@nf-lab/acme-forms",
                "target": "./legacy/_nf_lab_acme_forms.94Pg3JRWsX.js"
              },
              {
                "specifier": "@nf-lab/acme-animations",
                "target": "./legacy/_nf_lab_acme_animations.3hwm9OyNIq.js"
              }
            ]
          },
          {
            "scope": "./orders/",
            "imports": [
              {
                "specifier": "@nf-lab/acme-core",
                "target": "./orders/_nf_lab_acme_core.CBL6eVZ92m.js"
              },
              {
                "specifier": "@nf-lab/acme-common",
                "target": "./orders/_nf_lab_acme_common.xj02f30kez.js"
              },
              {
                "specifier": "@nf-lab/acme-router",
                "target": "./orders/_nf_lab_acme_router.LZMoTvZiG2.js"
              }
            ]
          },
          {
            "scope": "./invoices/",
            "imports": [
              {
                "specifier": "@nf-lab/acme-core",
                "target": "./orders/_nf_lab_acme_core.CBL6eVZ92m.js"
              },
              {
                "specifier": "@nf-lab/acme-common",
                "target": "./orders/_nf_lab_acme_common.xj02f30kez.js"
              },
              {
                "specifier": "@nf-lab/acme-router",
                "target": "./orders/_nf_lab_acme_router.LZMoTvZiG2.js"
              }
            ]
          },
          {
            "scope": "./contacts/",
            "imports": [
              {
                "specifier": "@nf-lab/acme-core",
                "target": "./orders/_nf_lab_acme_core.CBL6eVZ92m.js"
              },
              {
                "specifier": "@nf-lab/acme-common",
                "target": "./orders/_nf_lab_acme_common.xj02f30kez.js"
              },
              {
                "specifier": "@nf-lab/acme-router",
                "target": "./orders/_nf_lab_acme_router.LZMoTvZiG2.js"
              }
            ]
          },
          {
            "scope": "./onboarding/",
            "imports": [
              {
                "specifier": "@nf-lab/acme-core",
                "target": "./orders/_nf_lab_acme_core.CBL6eVZ92m.js"
              },
              {
                "specifier": "@nf-lab/acme-common",
                "target": "./orders/_nf_lab_acme_common.xj02f30kez.js"
              },
              {
                "specifier": "@nf-lab/acme-router",
                "target": "./orders/_nf_lab_acme_router.LZMoTvZiG2.js"
              }
            ]
          },
          {
            "scope": "./reports/",
            "imports": [
              {
                "specifier": "@nf-lab/acme-core",
                "target": "./orders/_nf_lab_acme_core.CBL6eVZ92m.js"
              },
              {
                "specifier": "@nf-lab/acme-common",
                "target": "./orders/_nf_lab_acme_common.xj02f30kez.js"
              },
              {
                "specifier": "@nf-lab/acme-router",
                "target": "./orders/_nf_lab_acme_router.LZMoTvZiG2.js"
              }
            ]
          }
        ],
        "integrity": {}
      }
    ],
    "effective": {
      "imports": [
        {
          "specifier": "@nf-lab/acme-core",
          "target": "http://localhost:4300/_nf_lab_acme_core._lqn63yOi7.js"
        },
        {
          "specifier": "@nf-lab/acme-common",
          "target": "http://localhost:4300/_nf_lab_acme_common.MmYG9ya5tm.js"
        },
        {
          "specifier": "@nf-lab/acme-router",
          "target": "http://localhost:4300/_nf_lab_acme_router.0upHOBLkHx.js"
        },
        {
          "specifier": "@nf-lab/acme-forms",
          "target": "http://localhost:4300/orders/_nf_lab_acme_forms.IWzwv3bFmd.js"
        },
        {
          "specifier": "@nf-lab/acme-animations",
          "target": "http://localhost:4300/orders/_nf_lab_acme_animations.iX1JyydcgC.js"
        },
        {
          "specifier": "products/./main",
          "target": "http://localhost:4300/products/main-JZC7PVTU.js"
        },
        {
          "specifier": "search/./main",
          "target": "http://localhost:4300/search/main-JZC7PVTU.js"
        },
        {
          "specifier": "settings/./main",
          "target": "http://localhost:4300/settings/main-JZC7PVTU.js"
        },
        {
          "specifier": "profile/./main",
          "target": "http://localhost:4300/profile/main-JZC7PVTU.js"
        },
        {
          "specifier": "cart/./main",
          "target": "http://localhost:4300/cart/main-JZC7PVTU.js"
        },
        {
          "specifier": "orders/./main",
          "target": "http://localhost:4300/orders/main-SJMAHDUI.js"
        },
        {
          "specifier": "invoices/./main",
          "target": "http://localhost:4300/invoices/main-SJMAHDUI.js"
        },
        {
          "specifier": "contacts/./main",
          "target": "http://localhost:4300/contacts/main-SJMAHDUI.js"
        },
        {
          "specifier": "onboarding/./main",
          "target": "http://localhost:4300/onboarding/main-SJMAHDUI.js"
        },
        {
          "specifier": "reports/./main",
          "target": "http://localhost:4300/reports/main-SJMAHDUI.js"
        },
        {
          "specifier": "legacy/./main",
          "target": "http://localhost:4300/legacy/main-SJMAHDUI.js"
        }
      ],
      "scopes": [
        {
          "scope": "http://localhost:4300/legacy/",
          "imports": [
            {
              "specifier": "@nf-lab/acme-core",
              "target": "http://localhost:4300/legacy/_nf_lab_acme_core.9F39ycxW9d.js"
            },
            {
              "specifier": "@nf-lab/acme-common",
              "target": "http://localhost:4300/legacy/_nf_lab_acme_common.zpK1ykCNPu.js"
            },
            {
              "specifier": "@nf-lab/acme-router",
              "target": "http://localhost:4300/legacy/_nf_lab_acme_router.AwUyup05cP.js"
            },
            {
              "specifier": "@nf-lab/acme-forms",
              "target": "http://localhost:4300/legacy/_nf_lab_acme_forms.94Pg3JRWsX.js"
            },
            {
              "specifier": "@nf-lab/acme-animations",
              "target": "http://localhost:4300/legacy/_nf_lab_acme_animations.3hwm9OyNIq.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/orders/",
          "imports": [
            {
              "specifier": "@nf-lab/acme-core",
              "target": "http://localhost:4300/orders/_nf_lab_acme_core.CBL6eVZ92m.js"
            },
            {
              "specifier": "@nf-lab/acme-common",
              "target": "http://localhost:4300/orders/_nf_lab_acme_common.xj02f30kez.js"
            },
            {
              "specifier": "@nf-lab/acme-router",
              "target": "http://localhost:4300/orders/_nf_lab_acme_router.LZMoTvZiG2.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/invoices/",
          "imports": [
            {
              "specifier": "@nf-lab/acme-core",
              "target": "http://localhost:4300/orders/_nf_lab_acme_core.CBL6eVZ92m.js"
            },
            {
              "specifier": "@nf-lab/acme-common",
              "target": "http://localhost:4300/orders/_nf_lab_acme_common.xj02f30kez.js"
            },
            {
              "specifier": "@nf-lab/acme-router",
              "target": "http://localhost:4300/orders/_nf_lab_acme_router.LZMoTvZiG2.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/contacts/",
          "imports": [
            {
              "specifier": "@nf-lab/acme-core",
              "target": "http://localhost:4300/orders/_nf_lab_acme_core.CBL6eVZ92m.js"
            },
            {
              "specifier": "@nf-lab/acme-common",
              "target": "http://localhost:4300/orders/_nf_lab_acme_common.xj02f30kez.js"
            },
            {
              "specifier": "@nf-lab/acme-router",
              "target": "http://localhost:4300/orders/_nf_lab_acme_router.LZMoTvZiG2.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/onboarding/",
          "imports": [
            {
              "specifier": "@nf-lab/acme-core",
              "target": "http://localhost:4300/orders/_nf_lab_acme_core.CBL6eVZ92m.js"
            },
            {
              "specifier": "@nf-lab/acme-common",
              "target": "http://localhost:4300/orders/_nf_lab_acme_common.xj02f30kez.js"
            },
            {
              "specifier": "@nf-lab/acme-router",
              "target": "http://localhost:4300/orders/_nf_lab_acme_router.LZMoTvZiG2.js"
            }
          ]
        },
        {
          "scope": "http://localhost:4300/reports/",
          "imports": [
            {
              "specifier": "@nf-lab/acme-core",
              "target": "http://localhost:4300/orders/_nf_lab_acme_core.CBL6eVZ92m.js"
            },
            {
              "specifier": "@nf-lab/acme-common",
              "target": "http://localhost:4300/orders/_nf_lab_acme_common.xj02f30kez.js"
            },
            {
              "specifier": "@nf-lab/acme-router",
              "target": "http://localhost:4300/orders/_nf_lab_acme_router.LZMoTvZiG2.js"
            }
          ]
        }
      ],
      "integrityFor": []
    }
  },
  "errors": []
};
