/**
 * Derives the checked-in SnapshotV1 fixture modules from the lossless
 * capture corpus (captures/, envelope `lab-lossless-capture/1`): one
 * fixture per lab scenario plus the frankenstein-live fixture from phase
 * 01-initial (the corpus validator enforces both live phases
 * byte-identical, so one fixture represents the deployment).
 *
 * Each fixture is produced by the REAL collector pipeline over a page
 * reconstructed from the capture (testing/capture-pipeline.ts, shared with
 * the fixture drift spec): buildCapturePage → PASSIVE_PROBE_SOURCE
 * (+ SHIM_MAP_PROBE_SOURCE when the probe reports a readable importShim,
 * mirroring ChromeSnapshotProvider) → mapProbeResult. Fixture == pipeline
 * output by construction; there is no separate hand-written projection.
 *
 * Deterministic: `capturedAt` comes from each capture envelope and the
 * mapper's output key order is spec-pinned, so re-running reproduces
 * byte-identical modules. Executed via scripts/derive-fixtures.mjs (the
 * esbuild launcher) from the repo root.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { deriveCaptureSnapshot } from '../projects/collector/src/testing/capture-pipeline';
import type { SnapshotV1 } from '../projects/devtools-bridge/src/lib/snapshot-v1';
import { LAB_CORPORA } from './lab-corpora.mjs';

// The corpus stamp is the exposed version from v4.7 on, the pinned commit before (8e5e0b3 = v4.6.0).
const orchestratorLabel = (stamp: string): string =>
  /^\d+\.\d+\.\d+/.test(stamp) ? `v${stamp}` : stamp === '8e5e0b3' ? 'v4.6.0 (8e5e0b3)' : stamp;

const MANIFEST_SCHEMA = 'lab-lossless-corpus/1';
const ENVELOPE_SCHEMA = 'lab-lossless-capture/1';
const FIXTURES_DIR = 'projects/devtools-bridge/src/lib/fixtures';
const GENERATED_NOTE =
  '// GENERATED by scripts/derive-fixtures.mjs — do not edit by hand; re-run the script.';
const PIPELINE_NOTE =
  '// Derived through the real collector pipeline (capture-seeded page → probe\n' +
  '// eval → mapProbeResult), so the fixture equals pipeline output by construction.';

function loadEnvelope(path: string): Record<string, any> {
  const envelope = JSON.parse(readFileSync(path, 'utf8'));
  if (envelope.schemaVersion !== ENVELOPE_SCHEMA) {
    throw new Error(
      `${path}: unknown envelope schemaVersion '${envelope.schemaVersion}' ` +
        `(this deriver understands only '${ENVELOPE_SCHEMA}')`,
    );
  }
  return envelope;
}

function deriveSnapshot(path: string, envelope: Record<string, any>): SnapshotV1 {
  const snapshot = deriveCaptureSnapshot(envelope);
  if (snapshot.errors.length > 0) {
    throw new Error(
      `${path}: derived snapshot carries collection errors — deriver bug, not corpus ` +
        `drift (the whole corpus projects error-free): ${JSON.stringify(snapshot.errors)}`,
    );
  }
  return snapshot;
}

function exportName(id: string): string {
  return id.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase()) + 'Fixture';
}

function writeFixture(id: string, banner: string, snapshot: SnapshotV1): void {
  const outFile = `${FIXTURES_DIR}/${id}.fixture.ts`;
  const module = `${banner}

import { SnapshotV1 } from '../snapshot-v1';

export const ${exportName(id)}: SnapshotV1 = ${JSON.stringify(snapshot, null, 2)};
`;
  writeFileSync(outFile, module);
  const runtime = snapshot.runtime;
  const participants = runtime
    ? Object.values(runtime.sharedExternals)
        .flatMap((packages) => Object.values(packages))
        .flatMap((external) => external.versions)
        .reduce((count, version) => count + version.remotes.length, 0)
    : 0;
  console.log(
    `wrote ${outFile} (generation ${runtime?.generation ?? 'n/a'}, ` +
      `remotes ${runtime ? Object.keys(runtime.remotes).length : 0}, ` +
      `participants ${participants}, ` +
      `imports ${snapshot.importMaps?.effective?.imports.length ?? 0}, ` +
      `integrity ${snapshot.importMaps?.effective?.integrityFor.length ?? 0})`,
  );
}

export function deriveFixtures(): void {
  for (const corpus of LAB_CORPORA) deriveCorpus(`captures/${corpus.manifest}`, corpus.live);
}

function deriveCorpus(manifestPath: string, withLive: boolean): void {
  let manifest: Record<string, any>;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  } catch {
    throw new Error(`cannot read ${manifestPath} — run from the repo root`);
  }
  if (manifest.schemaVersion !== MANIFEST_SCHEMA) {
    throw new Error(
      `${manifestPath}: unknown manifest schemaVersion '${manifest.schemaVersion}' ` +
        `(expected '${MANIFEST_SCHEMA}')`,
    );
  }

  for (const entry of manifest.captures) {
    const path = `captures/${entry.path}`;
    const envelope = loadEnvelope(path);
    const snapshot = deriveSnapshot(path, envelope);
    const banner = [
      GENERATED_NOTE,
      `// Source: ${path} (corpus run ${manifest.runId}),`,
      `// envelope ${ENVELOPE_SCHEMA}, orchestrator ${orchestratorLabel(manifest.source.orchestratorCommit)}, observed`,
      `// generation: ${snapshot.runtime?.generation ?? 'n/a'} — see captures/README.md for provenance.`,
      PIPELINE_NOTE,
    ].join('\n');
    writeFixture(entry.scenario, banner, snapshot);
  }
  if (!withLive) return;

  const live = manifest.liveCaptures;
  const initial = live.files.find((file: any) => file.phase === '01-initial');
  if (initial === undefined) {
    throw new Error(`${manifestPath}: liveCaptures carries no 01-initial phase`);
  }
  const livePath = `captures/${initial.path}`;
  const liveSnapshot = deriveSnapshot(livePath, loadEnvelope(livePath));
  if (liveSnapshot.runtime?.generation !== 'v4') {
    throw new Error(
      `${livePath}: expected the released v4 generation, ` +
        `derived '${liveSnapshot.runtime?.generation}'`,
    );
  }
  const provenance = live.provenance;
  const liveBanner = [
    GENERATED_NOTE,
    `// Source: ${livePath} — the public deployment`,
    `// ${provenance.captureUrl} captured ${provenance.captureDate}`,
    '// (deployment-dependent, not regenerable from checkouts; see',
    '// captures/frankenstein-live/provenance.json). Released orchestrator generation',
    `// (v4, \`file\`-spelling participants), best-known ${provenance.deployment.orchestrator.bestKnown.split(' via ')[0]}.`,
    '// The corpus validator enforces the two capture phases byte-identical, so this',
    '// one fixture represents both.',
    PIPELINE_NOTE,
  ].join('\n');
  writeFixture(live.scenarioId, liveBanner, liveSnapshot);
}
